project:
  type: website

website:
  # site-url: "https://yebelay.rbind.io/"
  title: "Home"
  description: "Welcome to EBS website"
  navbar:
    left:
      - text: "About Us"
        menu:
          - text: "Who We Are"
            href: pages/about/whoweare.qmd
          - text: "EBS board members"
            href: pages/about/ourteam.qmd
          - text: "Committee for SUSAN Conference"
            href: pages/about/commitee.qmd
      - href: pages/Registration.qmd
        text: "Registration"
      - href: pages/Abstracts.qmd
      - text: "Programmes"
        menu:
          - text: "Conference programme"
            href: pages/Programmes/conference.qmd
          - text: "Workshop programme"
            href: pages/Programmes/workshop.qmd
          - text: "other program"
            href: pages/Programmes/other.qmd

    right:
      - href: contact.qmd
        text: Contact
      - icon: twitter
        href: https://x.com/ethiopian_BS

  # Add email and phone to page footer
  page-footer:
    center: |
      <p>**Email:** <a href="mailto:ethiopianbiometricssociety@gmail.com">ethiopianbiometricssociety@gmail.com</a>; **Phone:** +251 92 553 9772 / +251 99 391 6717</p>
    border: false

  open-graph: false
  favicon: Icon.png

format:
  html:
    theme: [cosmo, theme.scss]
    toc: false
    link-external-newwindow: true
    metadata:
      pagetitle: "2025 SUSAN Conference"
