project:
  type: website

website:
 # site-url: "https://yebelay.rbind.io/"
  title: "Home"
  description: "Welcome to EBS website"
  navbar:
    left:
      - href: pages/about.qmd
      - href: pages/Registration.qmd
      - href: pages/Abstracts.qmd
      - href: pages/Programmes.qmd

    right:
      - href: contact.qmd
        text: Contact
      - icon: github
        href: https://github.com/Yebelay
  page-footer: 
    center: "Copyright 2024, EBS" 
    border: true
  open-graph: true
  favicon: Icon.png  
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    link-external-newwindow: true
    metadata:
      pagetitle: "2025 SUSAN Conference"

#header-includes:
#    - '<meta name="google-site-verification" content="X-rOcrlZrFLBgUJZQigAahlBd2T_crpYhrBMXuzl6IA" />'
