project:
  type: website

website:
  # site-url: "https://yebelay.rbind.io/"
  title: "Home"
  description: "Welcome to EBS website"
  navbar:
    left:
      - text: "About Us"
        menu:
          - text: "Who We Are"
            href: pages/about/whoweare.qmd
          - text: "EBS Executive Committee members"
            href: pages/about/ourteam.qmd
          - text: "Committees for SUSAN Conference"
            href: pages/about/commitees.qmd
      - href: pages/Registration.qmd
        text: "Registration"
      - href: pages/CallForAbstracts.qmd
        text: "Call for Abstracts"  
      - href: pages/Abstracts.qmd
      - text: "Programmes"
        menu:
          - text: "Conference programme"
            href: pages/Programmes/conference.qmd
          - text: "Workshop Overview"
            href: pages/Programmes/workshop-overview.qmd
          - text: "Workshop 1"
            href: pages/Programmes/workshop 1.qmd
          - text: "Workshop 2"
            href: pages/Programmes/workshop 2.qmd
          - text: "other program"
            href: pages/Programmes/other.qmd

    right:
      - href: contact.qmd
        text: Contact
      - icon: twitter
        href: https://x.com/ethiopian_BS

  # Add email and phone to page footer
  page-footer:
    center: |
     <div style="background-color: #f0f0f0; width: 100%; padding: 5px 0; text-align: center;">
      <p style="font-size: 1.2em; white-space: nowrap; margin: 0;"><strong>Email:</strong> <a href="mailto:ibsethiopiaregion@gmail.com" style="color: blue; text-decoration: underline;">ibsethiopiaregion@gmail.com</a> / <a href="mailto:ethiopianbiometricssociety@gmail.com" style="color: blue; text-decoration: underline;">ethiopianbiometricssociety@gmail.com</a></p>
      <p style="font-size: 1.2em; white-space: nowrap; margin: 0;"><strong>Phone:</strong> +251 99 391 6717 / +251 94 938 9536 / +27 78 257 3673 / +251 92 553 9772</p>
     </div> 
    border: false

  open-graph: false
  favicon: Icon.png

format:
  html:
    theme: [cosmo, theme.scss]
    toc: false
    link-external-newwindow: true
    metadata:
      pagetitle: "2025 SUSAN Conference"
