---
title: ""
---

<p style="color: red; font-size: 1.5em; font-weight: bold;">Workshop Overview</p>

<p><strong>The 19th Biennial Conference of the Sub-Saharan Network (SUSAN) of the International Biometrics Society (IBS)</strong><br>
Pre-Workshops at the SUSAN Conference<br>
<strong>Dates:</strong> 3–4 September 2025<br>
<strong>Location:</strong> Elilly International Hotel, Addis Ababa, Ethiopia
</p>

<p style="color: green; font-size: 1.4em; font-weight: bold;">Workshop 1: Data Wrangling and Data Visualizations in Health Data Science with R</p>

**Instructors:** Prof. Temesgen Zewotir, Prof. Henry Mwambi, Prof. Knowledge Chinhamu, Prof. Retius Chifurira, Prof. Faustin Habyarimana, Dr. Zelalem Getahun, Dr. Jesca Batidzirai, Dr. Mohanad Mohammed.  
**Description:** This **one-day** workshop provides intensive training on data wrangling and data visualization techniques in health data science using R.  
**Date:** 3 September 2025  
**Location:** Elilly International Hotel, Addis Ababa, Ethiopia

[Learn more about Workshop 1](workshop 1.qmd)

---

<p style="color: green; font-size: 1.4em; font-weight: bold;">Workshop 2: Linear Mixed Model Analysis of Correlated Data</p>

**Instructors:** Professor Alison Kelly and and Professor Clayton Forknall from the University of Queensland, Australia.  
**Description:** This **two-day** workshop focuses on linear mixed models for the analysis of correlated health data, including theory and practical applications.  
**Dates:** 3–4 September 2025  
**Location:** Elilly International Hotel, Addis Ababa, Ethiopia

[Learn more about Workshop 2](workshop 2.qmd)

---

<p style="color: green; font-size: 1.4em; font-weight: bold;">Workshop 3: Data Analysis, Modeling, Reporting, Output Production, and Online Content Development Using R</p>

**Instructors:** Dr. Rudradev Sengupta (rudradev.sengupta@one2treat.com) and Prof. Dr. Ziv Shkedy (ziv.shkedy@uhasselt.be).  
**Description:** This **one-day** workshop covers data analysis, modeling, report generation, and online content development using R.  
**Date:** 4 September 2025  
**Location:** Elilly International Hotel, Addis Ababa, Ethiopia

[Learn more about Workshop 3](workshop 3.qmd)

---

<p style="color: green; font-size: 1.4em; font-weight: bold;">Workshop 4: Geospatial Mapping with R for Health Data</p>

**Instructors:** Prof. Temesgen Zewotir, Prof. Henry Mwambi, Prof. Knowledge Chinhamu, Prof. Retius Chifurira, Prof. Faustin Habyarimana, Dr. Zelalem Getahun, Dr. Jesca Batidzirai, Dr. Mohanad Mohammed.  
**Description:** This **one-day** workshop introduces participants to geospatial mapping techniques for health data science using R.  
**Date:** 4 September 2025  
**Location:** Elilly International Hotel, Addis Ababa, Ethiopia

[Learn more about Workshop 4](workshop 4.qmd)

---

<p style="color: green; font-size: 1.4em; font-weight: bold;">Workshop 5: Modeling Longitudinal Data with Time-Dependent Covariates</p>

**Instructors:** Professor Ding-Geng Chen, Fellow of ASA and Distinguished Professor at UNC-Chapel Hill.  
**Description:** This **half-day** workshop explores the handling of time-varying covariates in statistical modeling, essential for longitudinal health studies.  
**Date:** 3 September 2025  (Afternoon).
**Location:** Elilly International Hotel, Addis Ababa, Ethiopia

[Learn more about Workshop 5](workshop 5.qmd)

---

<p style="color: green; font-size: 1.4em; font-weight: bold;">Workshop 6: Small Area Estimation using Official Statistics for Health Indicators</p>

**Instructors:** Seyifemickael Amare Yilema and Professor Ding-Geng Chen  
**Description:** This **half-day** workshop introduces Small Area Estimation (SAE) techniques for producing reliable health indicators in unplanned domains using survey and census data. The course will also cover spatial and multivariate model extensions, and introduce the Generalized SAE (GSAE) approach.  
**Dates:** 4 September 2025 (Morning). 
**Location:** Elilly International Hotel, Addis Ababa, Ethiopia

[Learn more about Workshop 6](workshop 6.qmd)


<p style="color: green; font-size: 1.4em; font-weight: bold;">Workshop 7: Computationally Efficient Bayesian Inference for Complex Biomedical Follow-Up Data: A Semiparametric Joint Modeling with INLA</p>

**Instructors:** Dr. Melkamu Molla Ferede and Professor Ding-Geng Chen  
**Description:** This **half-day** workshop offers hands-on training on semiparametric joint modeling using INLA in R. Participants will explore methods for modeling competing risks survival and skewed longitudinal data, and gain experience in fast, Bayesian inference for biomedical studies.  
**Date:** 4 September 2025 (Afternoon).    
**Location:** Elilly International Hotel, Addis Ababa, Ethiopia

[Learn more about Workshop 7](workshop 7.qmd)

