---
title: ""
---

<!--
<style>
@keyframes borderFlash {
    0% { border-color: red; }
    50% { border-color: yellow; }
    100% { border-color: red; }
}
.border-flash {
    border: 3px solid red;
    padding: 10px;
    display: inline-block;
    animation: borderFlash 1s infinite;
}
</style>


<p class="border-flash" style="color: blue; font-size: 1.8em; font-weight: bold; text-align: center;">
    Deadline Extended to 30 April 2025, 23:59, CEST
</p>

- We are happy to announce that the deadline for Abstract submissions has been extended to 30 April 2025, 23:59, CEST.

-->

<div style="text-align: center;">
<p style="color: green; font-size: 1.5em; font-weight: bold;"> Call for Abstract: IBS SUSAN2025 Conference </p>


<p style="color: red; font-size: 1.2em; font-weight: bold;"> The 19<sup>th</sup> Biennial Conference of the Sub-Saharan Network (SUSAN) of the International Biometrics Society (IBS) </p>

<p> 
Addis Ababa, Ethiopia<br>
3-8 September 2025
</p>

<p style="color: green; font-size: 1.4em; font-weight: bold;"> Conference theme: Biometrics and data science to enhance health and agriculture in
the developing world </p>

<p> Host: The IBS Ethiopia Region/Ethiopian Biometric Society </p>
</div>

<p style="color: green; font-size: 1.5em; font-weight: bold;"> About the Conference</p>

The IBS Ethiopia Region/Ethiopian Biometric Society (EBS) is pleased to invite you to attend the Conference of the Sub-Saharan Network (SUSAN) of the International Biometrics Society (IBS). The Conference will cover a wide range of classical and Bayesian statistical theory and methods and data science, their applications in life sciences (health and agriculture). 

The 19th Biennial IBS SUSAN 2025 Conference, an international event dedicated to advancements in biometrics and related fields. Organized in collaboration with the IBS, this conference aims to foster collaboration among researchers, academicians, practitioners, and students from around the globe. Participants will have the opportunity to share insights, discuss innovations, and explore future directions in these vital areas of study.

Join us in promoting knowledge exchange and networking on an international scale.

<p style="color: green; font-size: 1.5em; font-weight: bold;"> Sub themes:</p>

We invite original research papers and reviews on themes including, but not limited to:

- Biostatistics methodologies
-	Bioinformatics 
-	Data science (machine learning, AI, big data analytics, predictive modelling) 
-	Data analysis in biomedical and agriculture research
-	Ethical considerations in biometrics
-	Clinical trial study 
-	Design of experiments 
-	Bayesian methods 
-	Categorical data analysis and discrete models
-	Computation intensive methods and software development
-	Longitudinal data analysis/mixed effects model
-	Missing and incomplete data
-	Time to event models and multistate models
-	Joint outcome models
-	Causal inference
-	Mixture models
-	Statistical approaches to omics data
-	Small area estimation
-	Spatio-temporal modelling
-	Meta analysis
-	Disease burden estimation
-	Others

<p style="color: green; font-size: 1.5em; font-weight: bold;"> Submission Guidelines:</p>

- **Abstract submission:** Please submit a maximum of a 300-word abstract by 30 April 2025. 

- **Full paper submission:** Accepted abstracts will be invited for full paper submission by 15 June 2025.
- **Format:** Papers should be formatted according to the conference guidelines (details to be provided upon acceptance of abstracts).

<div style="font-family: Arial, sans-serif;">

<p style="font-weight: bold; color: green;">Important Dates</p>

<p><strong>Abstract Submission:</strong> <span style="color: red;">4 November 2024 - 30 April 2025</span></p>
<p><strong>Notification of Acceptance:</strong> <span style="color: red;">20 March - 20 May 2025</span></p>
<p><strong>Full Paper Submission Deadline:</strong> <span style="color: red;">20 July 2025</span></p>
<p><strong>Conference Dates:</strong> <span style="color: red;">3-8 September 2025</span></p>


<p style="font-weight: bold; color: green;">Abstract Submission</p>

- To submit your abstract, please go to the page: [Submit Abstract](Abstracts.qmd)


<p style="font-weight: bold; color: green;">Registration</p>

<p>Early bird registration will be available until <span style="color: red;">30 June 2025</span>. 

- To register, please visit our [Registration page →](Registration.qmd).

</div>

<div style="font-family: Arial, sans-serif;">

<p style="font-weight: bold; color: green;">Contact Information</p>

<p>For inquiries, please contact the organizing committee at: <a href="mailto:ibsethiopiaregion@gmail.com" style="color: blue; text-decoration: underline;">ibsethiopiaregion@gmail.com</a> / <a href="mailto:ethiopianbiometricssociety@gmail.com" style="color: blue; text-decoration: underline;">ethiopianbiometricssociety@gmail.com</a></p>

<p>For further information: +251 99 391 6717 / +251 94 938 9536 / +27 78 257 3673 / +251 92 553 9772</p>

<p style="font-weight: bold; color: green;">Conference Website</p>

<p>For more details and updates, please visit the conference <a href="https://susan2025ethiopia.netlify.app/" style="color: purple; text-decoration: underline;">Website</a>.</p>

<p>We look forward to your contributions and to an exciting conference in Addis Ababa.</p>

</div>

## Submit Your Abstract

<form action="https://docs.google.com/forms/d/e/1FAIpQLSctE-TraV6rwvSbSsNBMxo4UbAVS5Cb9h77wYsUff8BquOSgA/viewform1" target="_blank">

<button type="submit" class="submit-button">

Submit Abstract

</button>

</form>
